import Header from "./Layout/Header";
import localFont from 'next/font/local'

import SessionContext from "./Context/SessionContext";

import "./Styles/globals.css";
import "./Styles/KingPack.css";

const myFont = localFont({ src: './Styles/Font/MerriweatherSans.ttf'})

export const metadata = {
	title: "ZT PIZZA",
	description: "Generated by create next app",
};

import { getServerSession } from "next-auth";

export default async function RootLayout({ children }) {
	const session = await getServerSession();
	return (
		<html lang="pt-br">
			<body className={myFont.className}>
				<SessionContext>
					<Header />
					<main>{children}</main>
					<footer>copyright @ZT-PIZZA</footer>
				</SessionContext>
			</body>
		</html>
	);
}
